### ISSUE TITLE
Amazon auth

### ISSUE THREAD

**Issue by alexjmoore** [nicolai86/aws-chime-sdk#1]
Hi,

I have been playing with your SDK - super cool btw.  I have it working well, but ideally I'd like to use it with an account with Amazon auth which I know you don't support....in fact I got the nice message:

`2018/09/19 20:32:45 Failed to generate chime config: auth provider "amazon" not yet supported`

I have however found this implementation, which reading the comments implies that the Amazon auth is actually a simpler form submission, compared to the tokenization hassles of the WD based auth:

[https://github.com/awslabs/pidgin-chime/blob/master/chime/chime-signin.c](url)

Is this something that you are working on at all?

Thanks,
Alex

**Comment by nicolai86** [comment]
Hey Alex,

I have not yet looked at amazon auth simply because I have no account setup to use it.
But I'm happy to accept PRs which implement it :)

Best,
Raphael

**Comment by nicolai86** [comment]
fixed with latest commit. thanks @zendes !
